### ISSUE TITLE
Add shrinkWrap to ListView.builder

### ISSUE THREAD

**Issue by gehad-ahmed-mohamed** [mohamed-selim-a/ResponsiveGrid_Flutter#12]

**Comment by adeyinkabadmus** [comment]
If nesting scrollables is the problem, you can pass "scroll: false" to the ResponsiveGridList constructor which defaults to true. It builds with rows and columns instead of a ListView.builder if scroll is set to false.

```dart
ResponsiveGridList(
     scroll: false,
     ...
)
```
