### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by JohnGalt1717** [mohamed-selim-a/ResponsiveGrid_Flutter#13]
Hi there,

Any chance of getting this package updated for null safety support and published as beta like most other packages are doing?

**Comment by bayuly94** [comment]
use this

responsive_grid:
    git:
      url: git://github.com/mohamed-selim-a/ResponsiveGrid_Flutter.git
      ref: 22ee88eedca76cd70c0b9bacf7f506fd69ee20a6

**Comment by bayuly94** [comment]
use this

`responsive_grid:
    git:
      url: git://github.com/mohamed-selim-a/ResponsiveGrid_Flutter.git
      ref: 22ee88eedca76cd70c0b9bacf7f506fd69ee20a6`

**Comment by muhammad369** [comment]
Excuse me for the late response

I can't figure out whether the migration of the pkg requires the referencing app to also migrate to null safety or not

**Comment by mzdm** [comment]
> Excuse me for the late response
> 
> I can't figure out whether the migration of the pkg requires the referencing app to also migrate to null safety or not

Official guide https://dart.dev/null-safety/migration-guide

Not sure what you mean with referencing but I have already made a PR https://github.com/mohamed-selim-a/ResponsiveGrid_Flutter/pull/14 with all the changes.

**Comment by muhammad369** [comment]
I mean the app that is using the pkg
should it be migrated also to null safety to be able to use this version

**Comment by mzdm** [comment]
Yes all packages need to be migrated to migrate the package itself to null safety too. But I'm checking pubspec.yaml and don't see any package dependency?

**Comment by mzdm** [comment]
@mohamed-selim-a I've resolved conflicts from the 1.3.0 version. If there's anything needed to be addressed please let me know

**Comment by muhammad369** [comment]
Thanks for your PR
I'll merge it and close the issue
