### ISSUE TITLE
5 columns in a grid

### ISSUE THREAD

**Issue by tiagorossig** [mohamed-selim-a/ResponsiveGrid_Flutter#15]
Since the arguments for the ResponsiveGridCol are integers, it seems impossible to have a grid with 5 columns (which would require a value of 2.4). Am I missing something, or is this the case?

**Comment by muhammad369** [comment]
Yeah this is the case
The entire row wide is assumed to be 12 cells, and each col occupies equally divided number of cells, just as Bootstrap

you can use `ResponsiveGridList` and you specify the `desiredItemWidth` and `minSpacing` and the row will contain as many cols as the parent width can hold

**Comment by muhammad369** [comment]
Now you can set 5 cols in a row
I've added a new property `rowSegments` that is 12 by default 

for 5 cols in a row set it to 10 and set the col to occupy 2 cells, or set it to 20 and set the col to occupy 4 cells
whatever granularity works for you

**Comment by muhammad369** [comment]
included in version 1.3.0

**Comment by mzdm** [comment]
I think version 1.3.0 has some bug

**_buildGridList** example

before:

| before (1.2.1)  | after (1.3.0) |
| ------------- | ------------- |
| ![Screenshot_1617527286](https://user-images.githubusercontent.com/67197047/113504095-1d765900-9536-11eb-9ccf-0897f4156a47.png)  | ![Screenshot_1617527472](https://user-images.githubusercontent.com/67197047/113504143-79d97880-9536-11eb-9120-4fac18569286.png)
