### ISSUE TITLE
Grid Form Loses Data

### ISSUE THREAD

**Issue by alexalget** [mohamed-selim-a/ResponsiveGrid_Flutter#19]
I have an issue on Form with multiple TextFormInputs. When I previously wrote text in the inputs with a vertical layout (1 col per row) and then change the size of my window to multiple inputs per row it changes correctly the layout, but the data stays on the same line and causes to move to a different input. When i change back the view to 1 col per row i loose data from the inputs that were moved to the right size of other inputs in each row and the moved data returns back to their original inputs.

I hope I made clear the issue because its kind of confusing and hopefully there's a fix to it.

Thank you.

**Comment by MAFR1983** [comment]
I have the same problem, have you solved it?

**Comment by alexalget** [comment]
> I have the same problem, have you solved it?

Hi

Yes, I fixed it using a map of TextEditingController to maintain the values for each TextFormField, this works even if the app rebuilds when the MediaQuery changes.

You just need to declare and initilize the map and then assign them on the controller property of each field.
