### ISSUE TITLE
Major Bug on Inline Forms

### ISSUE THREAD

**Issue by markbulingit** [mohamed-selim-a/ResponsiveGrid_Flutter#23]
All the fields on last column are being reset when I resize the screen
![1](https://user-images.githubusercontent.com/91706339/155104884-2ea35229-dac2-4c8f-9fcc-52119c3bd1e8.png)

**Comment by alexbadia1** [comment]
Try updating the data in your state management tool as they update the text field and using a Text Controller to assign the initial value from your state managment tool. This way if there are any re-renders, the text field will always have the up to date value
