### ISSUE TITLE
Accept a scrollcontroller as constructor parameter

### ISSUE THREAD

**Issue by softlore** [mohamed-selim-a/ResponsiveGrid_Flutter#26]
I am using flutter 2.10.4 and currently working on a windows desktop app. I use **ResponsiveGridList** to build a grid. Whenever I scroll I am getting the following exception:

_**Another exception was thrown: The provided ScrollController is currently attached to more than on Scrollposition**_

I got a similar error when nesting **SingleChildScrollView** inside **Column** and this stackoverflow post https://stackoverflow.com/a/70772195/4435860 suggested to add **ScrollController**. Can you please check and update the constructor to accept a optional ScrollController?

**Comment by linhmanh92** [comment]
@softlore Has this issue been resolved?

**Comment by softlore** [comment]
[@linhmanh92](https://github.com/linhmanh92), I have modified the source code and added the modified version as a local dependancy in my project.
