### ISSUE TITLE
Large Item List

### ISSUE THREAD

**Issue by apgapg** [mohamed-selim-a/ResponsiveGrid_Flutter#3]
Thanks for this cool package. Its easy in comparison to GridView.
What i see you implemented this using columns and not listview which means if no. of items in list increases, this UI would lag. 
What are your thoughts on this?

**Comment by muhammad369** [comment]
You are welcome
you still can place it inside a list view

i didn't expect somebody may use it with large no. of items, so it's a layout

**Comment by muhammad369** [comment]
the `ResponsiveGridRow` is intended to contain 12 children at most
if you have many items, you shall place `ResponsiveGridRow`s inside a list
