### ISSUE TITLE
space between items of responsiveGridCol

### ISSUE THREAD

**Issue by marloncepeda** [mohamed-selim-a/ResponsiveGrid_Flutter#7]
Is there a way to generate spaces or padding between responsiveGridCol?

RGridRow(
children:[
 Item responsiveCol(),
  Space(),
 Item responsiveCol()
]

)

**Comment by muhammad369** [comment]
you can put empty ResponsiveGridCol() by setting a Container() as it's child

**Comment by markbulingit** [comment]
ResponsiveGridCol(
                md: 0,
                child: Container(width:10)
              ),
