### ISSUE TITLE
ResponsiveGridRow centers all childs

### ISSUE THREAD

**Issue by akshaybhange** [mohamed-selim-a/ResponsiveGrid_Flutter#8]
```
ResponsiveGridRow(
          children: [
            ResponsiveGridCol(
              lg: 6,
              xs: 12,
              child: Column(
                children: [
                  ImportantInfoCard(),// height 100px
                  AllLogCard(), // height 100px
                ],
              ),
            ),
            ResponsiveGridCol(
              lg: 6,
              xs: 12,
              child: AllClientsCard(), // height 500px
            )
          ],
        )
```

Here my first column has 2 childrens and 2nd col has 1 children.. but col1 has height of 200 px & col2 has height 500px then ResponsiveGridRow centers both the childs.. PFA image of my view
![Screenshot from 2020-04-13 20-37-10](https://user-images.githubusercontent.com/39375914/79131688-9da42b80-7dc6-11ea-8170-ec122e6756df.png)

**Comment by zkmark** [comment]
I have the same problem, did you manage to solve it?

![ftshop](https://user-images.githubusercontent.com/10190162/79714301-f6c40180-8295-11ea-891e-b4258d132ea5.png)

**Comment by akshaybhange** [comment]
not yet @zkmark . I'm waiting for the repo owner's reply..  @mohamed-selim-a  please give solution here.

**Comment by zkmark** [comment]
at the moment i use this similar package and it seems to work fine

https://github.com/rafaelsetragni/flutter_responsive

**Comment by akshaybhange** [comment]
@zkmark are you facing any issue with that repo ? is it compatible with flutter web?

**Comment by zkmark** [comment]
works fine

**Comment by muhammad369** [comment]
I'm so sorry for not being responsive that long
please use the latest version 1.2.0 you will find the problem solved
