### ISSUE TITLE
It does not compile for web

### ISSUE THREAD

**Issue by osinakayah** [mohamed-selim-a/ResponsiveGrid_Flutter#9]
It does not compile for web

**Comment by tyrone-ligph** [comment]
Mine too.
The relevant error-causing widget was:
`══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building LayoutBuilder:
'<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []

The relevant error-causing widget was:
  LayoutBuilder
  file:///Users/flutter_module/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_grid-1.2.0/li
  b/responsive_grid.dart:162:12`

**Comment by Fauzdar1** [comment]
In my case, it does compile but neither it shows dynamic list layout nor it supports state changes. The layout never renders is also a huge flaw of it. It should support a builder instead of a list.
